#!/usr/bin/env python3
"""Concatenate the skill into one self-contained markdown file.

The directory layout is for Claude Code. The single file is for claude.ai, a project
instruction, or a paste. One source of truth: edit the parts, rebuild the whole.

    python3 build_standalone.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "dist" / "claim-check-standalone.md"

PARTS = [
    ("SKILL.md", None),
    ("references/sources.md", "Appendix A: sources"),
    ("references/report_template.md", "Appendix B: report template"),
    ("competitors.yaml", "Appendix C: competitors (digest watchlist)"),
    ("claims.yaml", "Appendix D: claims (state)"),
]

HEADER = """<!-- claim-check, single-file build. Generated by build_standalone.py; edit the
parts, not this file. Paste into a Claude project, or keep alongside a repo.

To run it here: read the whole file, then follow the Procedure section. Appendix C says
who the digest watches; Appendix D is the state. Emit an updated Appendix D at the end
of the run so the next run has a baseline. -->

"""


def strip_frontmatter(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            return text[end + 5 :].lstrip("\n")
    return text


def build() -> None:
    OUT.parent.mkdir(exist_ok=True)
    chunks = [HEADER]
    for name, heading in PARTS:
        src = ROOT / name
        if not src.exists():
            raise SystemExit(f"missing part: {name}")
        body = src.read_text(encoding="utf-8")
        if heading:
            fence = "yaml" if name.endswith(".yaml") else None
            chunks.append(f"\n---\n\n# {heading}\n\n")
            chunks.append(f"```{fence}\n{body}\n```\n" if fence else strip_frontmatter(body))
        else:
            chunks.append(strip_frontmatter(body))
        print(f"  added: {name}")

    text = "\n".join(chunks)
    OUT.write_text(text, encoding="utf-8")
    print(f"\nwrote {OUT} ({len(text)//1024} KB, {len(text.split())} words)")


if __name__ == "__main__":
    build()
